// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dbquery.sql

package sqlQuery

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const conveyorConfigId = `-- name: ConveyorConfigId :one
SELECT cc.id
FROM peripheral_name pn
JOIN conveyor_config cc ON pn.id = cc.name
WHERE pn.name = ?
`

func (q *Queries) ConveyorConfigId(ctx context.Context, name sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, conveyorConfigId, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createConatiner = `-- name: CreateConatiner :exec
INSERT INTO cargo_info (
    id, 
    custom_id,
    status, 
    owner,
    metadata,
    updatedAt,
    custom_cargo_metadata_id,
    conveyor_configId
) VALUES (
    ?,?,?,?,?,?,?,?
)
`

type CreateConatinerParams struct {
	ID                    string
	CustomID              sql.NullString
	Status                CargoInfoStatus
	Owner                 CargoInfoOwner
	Metadata              json.RawMessage
	Updatedat             time.Time
	CustomCargoMetadataID sql.NullString
	ConveyorConfigid      sql.NullString
}

func (q *Queries) CreateConatiner(ctx context.Context, arg CreateConatinerParams) error {
	_, err := q.db.ExecContext(ctx, createConatiner,
		arg.ID,
		arg.CustomID,
		arg.Status,
		arg.Owner,
		arg.Metadata,
		arg.Updatedat,
		arg.CustomCargoMetadataID,
		arg.ConveyorConfigid,
	)
	return err
}

const createConatinerHistory = `-- name: CreateConatinerHistory :exec
INSERT INTO cargo_history (
    id,
    cargo_id,
    action,
    actor,
    description
) VALUES (
    ?,?,?,?,?
)
`

type CreateConatinerHistoryParams struct {
	ID          string
	CargoID     string
	Action      CargoHistoryAction
	Actor       sql.NullString
	Description sql.NullString
}

func (q *Queries) CreateConatinerHistory(ctx context.Context, arg CreateConatinerHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createConatinerHistory,
		arg.ID,
		arg.CargoID,
		arg.Action,
		arg.Actor,
		arg.Description,
	)
	return err
}

const currentScriptId = `-- name: CurrentScriptId :one
SELECT 
    id 
FROM mission_script
WHERE isUsing = 1
LIMIT 1
`

func (q *Queries) CurrentScriptId(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, currentScriptId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const currentScriptName = `-- name: CurrentScriptName :one
SELECT 
    name 
FROM mission_script
WHERE isUsing = 1
LIMIT 1
`

func (q *Queries) CurrentScriptName(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, currentScriptName)
	var name string
	err := row.Scan(&name)
	return name, err
}

const peripheralName = `-- name: PeripheralName :one
SELECT id, name, description, quantity, type, group_id, load_priority, offload_priority FROM peripheral_name WHERE name = ?
`

func (q *Queries) PeripheralName(ctx context.Context, name sql.NullString) (PeripheralName, error) {
	row := q.db.QueryRowContext(ctx, peripheralName, name)
	var i PeripheralName
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Type,
		&i.GroupID,
		&i.LoadPriority,
		&i.OffloadPriority,
	)
	return i, err
}
