// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlQuery

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type CargoHistoryAction string

const (
	CargoHistoryActionCREATED  CargoHistoryAction = "CREATED"
	CargoHistoryActionTRANSFER CargoHistoryAction = "TRANSFER"
	CargoHistoryActionLOAD     CargoHistoryAction = "LOAD"
	CargoHistoryActionOFFLOAD  CargoHistoryAction = "OFFLOAD"
	CargoHistoryActionSHIFTED  CargoHistoryAction = "SHIFTED"
	CargoHistoryActionUPDATED  CargoHistoryAction = "UPDATED"
)

func (e *CargoHistoryAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CargoHistoryAction(s)
	case string:
		*e = CargoHistoryAction(s)
	default:
		return fmt.Errorf("unsupported scan type for CargoHistoryAction: %T", src)
	}
	return nil
}

type NullCargoHistoryAction struct {
	CargoHistoryAction CargoHistoryAction
	Valid              bool // Valid is true if CargoHistoryAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCargoHistoryAction) Scan(value interface{}) error {
	if value == nil {
		ns.CargoHistoryAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CargoHistoryAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCargoHistoryAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CargoHistoryAction), nil
}

type CargoInfoOwner string

const (
	CargoInfoOwnerCONVEYOR CargoInfoOwner = "CONVEYOR"
	CargoInfoOwnerELEVATOR CargoInfoOwner = "ELEVATOR"
	CargoInfoOwnerSHIFT    CargoInfoOwner = "SHIFT"
	CargoInfoOwnerAMR      CargoInfoOwner = "AMR"
	CargoInfoOwnerSTORAGE  CargoInfoOwner = "STORAGE"
)

func (e *CargoInfoOwner) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CargoInfoOwner(s)
	case string:
		*e = CargoInfoOwner(s)
	default:
		return fmt.Errorf("unsupported scan type for CargoInfoOwner: %T", src)
	}
	return nil
}

type NullCargoInfoOwner struct {
	CargoInfoOwner CargoInfoOwner
	Valid          bool // Valid is true if CargoInfoOwner is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCargoInfoOwner) Scan(value interface{}) error {
	if value == nil {
		ns.CargoInfoOwner, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CargoInfoOwner.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCargoInfoOwner) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CargoInfoOwner), nil
}

type CargoInfoStatus string

const (
	CargoInfoStatusPRESPAWN   CargoInfoStatus = "PRE_SPAWN"
	CargoInfoStatusONAMR      CargoInfoStatus = "ON_AMR"
	CargoInfoStatusATLOCATION CargoInfoStatus = "AT_LOCATION"
	CargoInfoStatusSHIFT      CargoInfoStatus = "SHIFT"
)

func (e *CargoInfoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CargoInfoStatus(s)
	case string:
		*e = CargoInfoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CargoInfoStatus: %T", src)
	}
	return nil
}

type NullCargoInfoStatus struct {
	CargoInfoStatus CargoInfoStatus
	Valid           bool // Valid is true if CargoInfoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCargoInfoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CargoInfoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CargoInfoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCargoInfoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CargoInfoStatus), nil
}

type LocAreatype string

const (
	LocAreatypeCHARGING      LocAreatype = "CHARGING"
	LocAreatypeDISPATCH      LocAreatype = "DISPATCH"
	LocAreatypeSTANDBY       LocAreatype = "STANDBY"
	LocAreatypeSTORAGE       LocAreatype = "STORAGE"
	LocAreatypeEXTRA         LocAreatype = "EXTRA"
	LocAreatypeELEVATOR      LocAreatype = "ELEVATOR"
	LocAreatypeROBOTICARM    LocAreatype = "ROBOTIC_ARM"
	LocAreatypeCONVEYOR      LocAreatype = "CONVEYOR"
	LocAreatypeLIFTGATE      LocAreatype = "LIFT_GATE"
	LocAreatypeGATEWAITPOINT LocAreatype = "GATE_WAIT_POINT"
	LocAreatypePALLETIZER    LocAreatype = "PALLETIZER"
	LocAreatypeROTATETABLE   LocAreatype = "ROTATE_TABLE"
	LocAreatypeSTACK         LocAreatype = "STACK"
)

func (e *LocAreatype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocAreatype(s)
	case string:
		*e = LocAreatype(s)
	default:
		return fmt.Errorf("unsupported scan type for LocAreatype: %T", src)
	}
	return nil
}

type NullLocAreatype struct {
	LocAreatype LocAreatype
	Valid       bool // Valid is true if LocAreatype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocAreatype) Scan(value interface{}) error {
	if value == nil {
		ns.LocAreatype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocAreatype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocAreatype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocAreatype), nil
}

type MockWcsStationMachineType string

const (
	MockWcsStationMachineTypeCONVEYOR      MockWcsStationMachineType = "CONVEYOR"
	MockWcsStationMachineTypeLIFTGATE      MockWcsStationMachineType = "LIFT_GATE"
	MockWcsStationMachineTypeGATEWAITPOINT MockWcsStationMachineType = "GATE_WAIT_POINT"
	MockWcsStationMachineTypeROBOTICARM    MockWcsStationMachineType = "ROBOTIC_ARM"
	MockWcsStationMachineTypeELEVATOR      MockWcsStationMachineType = "ELEVATOR"
	MockWcsStationMachineTypePALLETIZER    MockWcsStationMachineType = "PALLETIZER"
	MockWcsStationMachineTypeCHARGING      MockWcsStationMachineType = "CHARGING"
	MockWcsStationMachineTypeSTACK         MockWcsStationMachineType = "STACK"
)

func (e *MockWcsStationMachineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MockWcsStationMachineType(s)
	case string:
		*e = MockWcsStationMachineType(s)
	default:
		return fmt.Errorf("unsupported scan type for MockWcsStationMachineType: %T", src)
	}
	return nil
}

type NullMockWcsStationMachineType struct {
	MockWcsStationMachineType MockWcsStationMachineType
	Valid                     bool // Valid is true if MockWcsStationMachineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMockWcsStationMachineType) Scan(value interface{}) error {
	if value == nil {
		ns.MockWcsStationMachineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MockWcsStationMachineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMockWcsStationMachineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MockWcsStationMachineType), nil
}

type PeripheralNameType string

const (
	PeripheralNameTypeCHARGING      PeripheralNameType = "CHARGING"
	PeripheralNameTypeDISPATCH      PeripheralNameType = "DISPATCH"
	PeripheralNameTypeSTANDBY       PeripheralNameType = "STANDBY"
	PeripheralNameTypeSTORAGE       PeripheralNameType = "STORAGE"
	PeripheralNameTypeEXTRA         PeripheralNameType = "EXTRA"
	PeripheralNameTypeELEVATOR      PeripheralNameType = "ELEVATOR"
	PeripheralNameTypeROBOTICARM    PeripheralNameType = "ROBOTIC_ARM"
	PeripheralNameTypeCONVEYOR      PeripheralNameType = "CONVEYOR"
	PeripheralNameTypeLIFTGATE      PeripheralNameType = "LIFT_GATE"
	PeripheralNameTypeGATEWAITPOINT PeripheralNameType = "GATE_WAIT_POINT"
	PeripheralNameTypePALLETIZER    PeripheralNameType = "PALLETIZER"
	PeripheralNameTypeROTATETABLE   PeripheralNameType = "ROTATE_TABLE"
	PeripheralNameTypeSTACK         PeripheralNameType = "STACK"
)

func (e *PeripheralNameType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeripheralNameType(s)
	case string:
		*e = PeripheralNameType(s)
	default:
		return fmt.Errorf("unsupported scan type for PeripheralNameType: %T", src)
	}
	return nil
}

type NullPeripheralNameType struct {
	PeripheralNameType PeripheralNameType
	Valid              bool // Valid is true if PeripheralNameType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeripheralNameType) Scan(value interface{}) error {
	if value == nil {
		ns.PeripheralNameType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeripheralNameType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeripheralNameType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeripheralNameType), nil
}

type TimelineEventType string

const (
	TimelineEventTypeGROUP TimelineEventType = "GROUP"
	TimelineEventTypeFIXED TimelineEventType = "FIXED"
)

func (e *TimelineEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimelineEventType(s)
	case string:
		*e = TimelineEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for TimelineEventType: %T", src)
	}
	return nil
}

type NullTimelineEventType struct {
	TimelineEventType TimelineEventType
	Valid             bool // Valid is true if TimelineEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimelineEventType) Scan(value interface{}) error {
	if value == nil {
		ns.TimelineEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimelineEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimelineEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimelineEventType), nil
}

type TimelineMissionType string

const (
	TimelineMissionTypeDYNAMIC      TimelineMissionType = "DYNAMIC"
	TimelineMissionTypeNOTIFY       TimelineMissionType = "NOTIFY"
	TimelineMissionTypeNORMAL       TimelineMissionType = "NORMAL"
	TimelineMissionTypeGROUPTOGROUP TimelineMissionType = "GROUP_TO_GROUP"
)

func (e *TimelineMissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimelineMissionType(s)
	case string:
		*e = TimelineMissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TimelineMissionType: %T", src)
	}
	return nil
}

type NullTimelineMissionType struct {
	TimelineMissionType TimelineMissionType
	Valid               bool // Valid is true if TimelineMissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimelineMissionType) Scan(value interface{}) error {
	if value == nil {
		ns.TimelineMissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimelineMissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimelineMissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimelineMissionType), nil
}

type TimelineType string

const (
	TimelineTypeSPAWNCARGO      TimelineType = "SPAWN_CARGO"
	TimelineTypeSHIFTCARGO      TimelineType = "SHIFT_CARGO"
	TimelineTypeMISSION         TimelineType = "MISSION"
	TimelineTypeSPAWNCARGOGROUP TimelineType = "SPAWN_CARGO_GROUP"
	TimelineTypeSHIFTCARGOGROUP TimelineType = "SHIFT_CARGO_GROUP"
)

func (e *TimelineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimelineType(s)
	case string:
		*e = TimelineType(s)
	default:
		return fmt.Errorf("unsupported scan type for TimelineType: %T", src)
	}
	return nil
}

type NullTimelineType struct {
	TimelineType TimelineType
	Valid        bool // Valid is true if TimelineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimelineType) Scan(value interface{}) error {
	if value == nil {
		ns.TimelineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimelineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimelineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimelineType), nil
}

type TitlebridgelocMissiontype string

const (
	TitlebridgelocMissiontypeLoad    TitlebridgelocMissiontype = "load"
	TitlebridgelocMissiontypeOffload TitlebridgelocMissiontype = "offload"
)

func (e *TitlebridgelocMissiontype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TitlebridgelocMissiontype(s)
	case string:
		*e = TitlebridgelocMissiontype(s)
	default:
		return fmt.Errorf("unsupported scan type for TitlebridgelocMissiontype: %T", src)
	}
	return nil
}

type NullTitlebridgelocMissiontype struct {
	TitlebridgelocMissiontype TitlebridgelocMissiontype
	Valid                     bool // Valid is true if TitlebridgelocMissiontype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTitlebridgelocMissiontype) Scan(value interface{}) error {
	if value == nil {
		ns.TitlebridgelocMissiontype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TitlebridgelocMissiontype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTitlebridgelocMissiontype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TitlebridgelocMissiontype), nil
}

type UserinfoStatus string

const (
	UserinfoStatusGENERALLY UserinfoStatus = "GENERALLY"
	UserinfoStatusENGINEER  UserinfoStatus = "ENGINEER"
	UserinfoStatusADMIN     UserinfoStatus = "ADMIN"
)

func (e *UserinfoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserinfoStatus(s)
	case string:
		*e = UserinfoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserinfoStatus: %T", src)
	}
	return nil
}

type NullUserinfoStatus struct {
	UserinfoStatus UserinfoStatus
	Valid          bool // Valid is true if UserinfoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserinfoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserinfoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserinfoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserinfoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserinfoStatus), nil
}

type AbortMissionWhenHasCargoTask struct {
	ID             string
	Active         bool
	AmrID          json.RawMessage
	MissionTitleID string
}

type AlarmIDHistory struct {
	ID         string
	AmrID      string
	Createdat  time.Time
	Resolvedat sql.NullTime
	IsActive   bool
	AlarmID    int32
}

type AlarmIDList struct {
	ID           int32
	IsOpenBuzzer bool
	InfoCh       string
	InfoEn       string
	SolutionCh   string
	SolutionEn   string
}

type Backuplog struct {
	ID       string
	Createat time.Time
	Dbpath   string
}

type Beforeleftstation struct {
	ID             string
	Active         bool
	Amrid          json.RawMessage
	Missiontitleid sql.NullString
}

type CargoHistory struct {
	ID          string
	CargoID     string
	Action      CargoHistoryAction
	Description sql.NullString
	Actor       sql.NullString
	Timestamp   time.Time
}

type CargoInfo struct {
	ID                    string
	IsReal                bool
	Status                CargoInfoStatus
	Metadata              json.RawMessage
	Createdat             time.Time
	Updatedat             time.Time
	RegisterRobotID       sql.NullString
	ScriptRobotID         sql.NullString
	Shelfconfigid         sql.NullString
	CustomCargoMetadataID sql.NullString
	ConveyorConfigid      sql.NullString
	ElevatorConfigID      sql.NullString
	CustomID              sql.NullString
	Owner                 CargoInfoOwner
	StackConfigID         sql.NullString
	PlacementOrder        int32
}

type Category struct {
	ID      string
	Tagname string
	Color   string
}

type ChargeMission struct {
	ID                        string
	Active                    bool
	Aggressivethreshold       sql.NullInt32
	Passivethreshold          sql.NullInt32
	Fullthreshold             sql.NullInt32
	Availablegettaskthreshold sql.NullInt32
	Missiontitleid            sql.NullString
}

type ChargeStationConfig struct {
	ID               string
	StationID        string
	Disable          bool
	ChargeSpeedMs    int32
	Name             string
	MockWcsStationid sql.NullString
}

type ConveyorConfig struct {
	ID              string
	Hascargo        bool
	Disable         bool
	ForkHeight      int32
	ActiveLoad      bool
	ActiveOffload   bool
	LoadingTimeMs   int32
	UnloadingTimeMs int32
	IsSpawnCargo    bool
	SpawnTimeMs     int32
	ActiveShift     bool
	ShiftTimeMs     int32
	ShiftLocationID sql.NullString
	Name            string
}

type CustomCargoMetadatum struct {
	ID         string
	IsDefault  bool
	CustomName string
	Format     json.RawMessage
	UniqueKey  sql.NullString
}

type CycleMission struct {
	ID      string
	Name    string
	Payload json.RawMessage
}

type Direction struct {
	ID  string
	Yaw float64
}

type DynamicMissionBridge struct {
	ID                string
	Order             int32
	LoadNameID        sql.NullString
	OffloadNameID     sql.NullString
	TimelineMissionID sql.NullString
}

type DynamicMissionPeripheralGroupForTimeline struct {
	ID                string
	Range             sql.NullString
	ActiveInterval    int32
	TimelineMissionID string
}

type ElevatorConfig struct {
	ID              string
	Hascargo        bool
	Disable         bool
	ForkHeight      int32
	LoadingTimeMs   int32
	UnloadingTimeMs int32
	Name            string
}

type FeedbackTask struct {
	ID             int32
	AmrID          json.RawMessage
	ObtainID       json.RawMessage
	Active         bool
	MissionTitleID string
}

type FeedbackTaskAnytime struct {
	ID             int32
	AmrID          json.RawMessage
	ObtainID       json.RawMessage
	Active         bool
	MissionTitleID string
}

type GateWaitPointConfig struct {
	ID      string
	Disable bool
	Name    string
}

type GooseDbVersion struct {
	ID        uint64
	VersionID int64
	IsApplied bool
	Tstamp    sql.NullTime
}

type IdleTask struct {
	ID              string
	Active          bool
	IdleMin         float64
	PreventLocation json.RawMessage
	MissionTitleID  string
}

type LiftGateConfig struct {
	ID      string
	Disable bool
	Name    string
}

type LoadOffloadForTimelineGroup struct {
	ID             string
	Order          int32
	LoadGroupID    string
	OffloadGroupID string
	DmpgID         string
}

type Loc struct {
	ID                string
	Name              sql.NullString
	Locationid        string
	X                 float64
	Y                 float64
	Canrotate         bool
	Connectedroadids  json.RawMessage
	Areatype          LocAreatype
	Cost              float64
	Translatex        float64
	Translatey        float64
	Rotate            int32
	Scale             float64
	FlexDirection     string
	PlacementPriority int32
	Relationships     json.RawMessage
	Dirid             sql.NullString
	Shelfid           sql.NullString
	PreparePointID    sql.NullString
	MissionScriptID   sql.NullString
}

type Map struct {
	ID         string
	Filename   string
	Isusing    bool
	Maporiginx float64
	Maporiginy float64
	Mapwidth   int32
	Mapheight  int32
	Scale      int32
	Scrollx    int32
	Scrolly    int32
}

type Mission struct {
	ID                     string
	Order                  sql.NullInt32
	Priority               sql.NullInt32
	SendBy                 int32
	Amrid                  string
	Status                 int32
	Task                   json.RawMessage
	FullName               json.RawMessage
	SubName                sql.NullString
	Category               json.RawMessage
	Manualmode             bool
	Emergencybtn           bool
	Recoverybtn            bool
	Createdat              sql.NullTime
	Assignedat             sql.NullTime
	Startedat              sql.NullTime
	Completedat            sql.NullTime
	Warningidlist          json.RawMessage
	Batterycost            int32
	Batteryratewhenstarted int32
	Totaldistancetraveled  float64
	SimulateScale          int32
	Info                   json.RawMessage
	Message                sql.NullString
	CancelReason           sql.NullInt32
}

type MissionFolder struct {
	ID   string
	Name string
}

type MissionScript struct {
	ID         string
	Name       string
	Isusing    bool
	StartPoint sql.NullString
}

type MissionSlice struct {
	ID             string
	ProcessOrder   int32
	Disable        bool
	Detail         json.RawMessage
	Missiontitleid string
}

type Missiontitle struct {
	ID              string
	Name            string
	RobotID         sql.NullString
	MissionFolderID sql.NullString
}

type Missiontitlebridgecategory struct {
	ID             string
	Missiontitleid sql.NullString
	Categoryid     sql.NullString
}

type MockWcsStation struct {
	ID              string
	MachineType     MockWcsStationMachineType
	DelayMs         int32
	IsEnabled       bool
	Sourceid        string
	MissionScriptID sql.NullString
	ConveyorID      sql.NullString
	ElevatorID      sql.NullString
	StackID         sql.NullString
	ChargeStationID sql.NullString
	LiftGateID      sql.NullString
	GateWaitPointID sql.NullString
}

type PeripheralGroup struct {
	ID              string
	Name            string
	Description     sql.NullString
	MissionScriptID string
}

type PeripheralName struct {
	ID              string
	Name            sql.NullString
	Description     string
	Quantity        int32
	Type            PeripheralNameType
	GroupID         sql.NullString
	LoadPriority    int32
	OffloadPriority int32
}

type RegisterRobot struct {
	ID                     string
	FullName               string
	Serialnum              string
	IsEnable               bool
	MaintenanceLevel       int32
	RobotTypeID            string
	ChargeMissionSettingID sql.NullString
	IdleMissionSettingID   sql.NullString
}

type Road struct {
	ID              string
	Roadid          sql.NullString
	Priority        int32
	Startx          string
	Endto           string
	Roadtype        string
	Disabled        bool
	Limit           bool
	Cost            float64
	Validyawlist    json.RawMessage
	Tolerance       float64
	Maxspeed        float64
	X1              float64
	Y1              float64
	X2              float64
	Y2              float64
	MissionScriptID sql.NullString
}

type RobotType struct {
	ID     string
	Name   string
	Value  string
	Height float64
	Length float64
	Width  float64
}

type Scheduletask struct {
	ID             string
	Active         bool
	Schedule       string
	Amrid          json.RawMessage
	Missiontitleid sql.NullString
}

type ScriptRobot struct {
	ID                      string
	FullName                string
	IsInScript              bool
	LoadSpeed               int32
	OffloadSpeed            int32
	MoveSpeed               float64
	ScriptPlacementLocation string
	Serialnum               string
	MaintenanceLevel        int32
	MissionScriptID         string
	ChargeMissionSettingID  sql.NullString
	IdleMissionSettingID    sql.NullString
	RobotTypeID             sql.NullString
}

type Shelf struct {
	ID              string
	Shelfcategoryid sql.NullString
}

type Shelfcategory struct {
	ID         string
	Name       string
	ShelfStyle string
}

type Shelfconfig struct {
	ID            string
	Level         int32
	Hascargo      bool
	Disable       bool
	CargoLimit    int32
	Shelfid       sql.NullString
	Shelfheightid string
	Name          string
}

type Shelfheight struct {
	ID              string
	Height          int32
	Shelfcategoryid sql.NullString
}

type ShiftCargoPeripheralGroupBridge struct {
	ID                string
	Range             sql.NullString
	ActiveInterval    int32
	IsShiftAll        bool
	ShiftNumber       int32
	TimelineID        string
	PeripheralGroupID string
}

type SimulationResult struct {
	ID                 string
	AmrStat            json.RawMessage
	Starttime          string
	Endtime            string
	TotalCargosCarried int32
	MissionSuccessRate int32
	TotalMissionCount  int32
	CompletedMissions  int32
	Createdat          time.Time
}

type SpawnCargoPeripheralGroupBridge struct {
	ID                string
	Range             sql.NullString
	ActiveInterval    int32
	IsSpawnAll        bool
	SpawnNumber       int32
	TimelineID        string
	PeripheralGroupID string
	SpawnCargoInfoID  sql.NullString
}

type StackConfig struct {
	ID               string
	Disable          bool
	Heights          json.RawMessage
	StackCount       int32
	Name             string
	MockWcsStationid sql.NullString
}

type Tagsetting struct {
	ID            string
	ZoneID        string
	SpeedLimit    sql.NullFloat64
	HightLimit    sql.NullFloat64
	Limitnum      sql.NullInt32
	ForbiddenCar  json.RawMessage
	ViewAvailable sql.NullString
}

type Test struct {
	ID  string
	Msg string
}

type Timeline struct {
	ID                 string
	Timestamp          string
	EventType          TimelineEventType
	Type               TimelineType
	IsEnable           bool
	StyleRow           int32
	ShiftPeripheralID  sql.NullString
	SimulationResultID sql.NullString
	ScriptID           string
}

type TimelineMission struct {
	ID             string
	Priority       int32
	Type           TimelineMissionType
	AmrRelateID    sql.NullString
	MissionTitleID sql.NullString
	NotifyNameID   sql.NullString
	TimelineID     string
}

type TimelineSpawnCargo struct {
	ID               string
	PeripheralNameID string
	SpawnCargoInfoID sql.NullString
	TimelineID       string
}

type Titlebridgeloc struct {
	ID           string
	Missiontype  NullTitlebridgelocMissiontype
	Missionorder int32
	Titleid      sql.NullString
	Locid        sql.NullString
}

type TopicTask struct {
	ID             string
	Active         bool
	AmrID          json.RawMessage
	TopicID        int32
	MissionTitleID string
}

type Userinfo struct {
	ID       string
	Account  string
	Password string
	Token    string
	Status   UserinfoStatus
}

type WarningIDHistory struct {
	ID         string
	AmrID      string
	Createdat  time.Time
	Resolvedat sql.NullTime
	IsActive   bool
	WarningID  int32
}

type WarningIDList struct {
	ID           int32
	IsOpenBuzzer bool
	InfoCh       string
	InfoEn       string
	SolutionCh   string
	SolutionEn   string
}

type Zone struct {
	ID              string
	Name            string
	StartPointX     float64
	StartPointY     float64
	EndPointX       float64
	EndPointY       float64
	BackgroundColor string
	Category        json.RawMessage
	MissionScriptID sql.NullString
	Layer           string
	LidarBack       bool
	LidarFront      bool
}
