// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: yfy.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PaperCount    int32                  `protobuf:"varint,2,opt,name=paper_count,json=paperCount,proto3" json:"paper_count,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	BatchNo       string                 `protobuf:"bytes,4,opt,name=batch_no,json=batchNo,proto3" json:"batch_no,omitempty"`
	WarehouseNo   string                 `protobuf:"bytes,5,opt,name=warehouse_no,json=warehouseNo,proto3" json:"warehouse_no,omitempty"`
	TrayType      string                 `protobuf:"bytes,6,opt,name=tray_type,json=trayType,proto3" json:"tray_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_yfy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yfy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_yfy_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetPaperCount() int32 {
	if x != nil {
		return x.PaperCount
	}
	return 0
}

func (x *OrderInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OrderInfo) GetBatchNo() string {
	if x != nil {
		return x.BatchNo
	}
	return ""
}

func (x *OrderInfo) GetWarehouseNo() string {
	if x != nil {
		return x.WarehouseNo
	}
	return ""
}

func (x *OrderInfo) GetTrayType() string {
	if x != nil {
		return x.TrayType
	}
	return ""
}

type CallTray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrayType      string                 `protobuf:"bytes,1,opt,name=tray_type,json=trayType,proto3" json:"tray_type,omitempty"`
	TrayQty       int32                  `protobuf:"varint,2,opt,name=tray_qty,json=trayQty,proto3" json:"tray_qty,omitempty"`
	WorkStation   string                 `protobuf:"bytes,3,opt,name=work_station,json=workStation,proto3" json:"work_station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTray) Reset() {
	*x = CallTray{}
	mi := &file_yfy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTray) ProtoMessage() {}

func (x *CallTray) ProtoReflect() protoreflect.Message {
	mi := &file_yfy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTray.ProtoReflect.Descriptor instead.
func (*CallTray) Descriptor() ([]byte, []int) {
	return file_yfy_proto_rawDescGZIP(), []int{1}
}

func (x *CallTray) GetTrayType() string {
	if x != nil {
		return x.TrayType
	}
	return ""
}

func (x *CallTray) GetTrayQty() int32 {
	if x != nil {
		return x.TrayQty
	}
	return 0
}

func (x *CallTray) GetWorkStation() string {
	if x != nil {
		return x.WorkStation
	}
	return ""
}

type Replenish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrayQty       int32                  `protobuf:"varint,2,opt,name=tray_qty,json=trayQty,proto3" json:"tray_qty,omitempty"`
	WorkStation   string                 `protobuf:"bytes,3,opt,name=work_station,json=workStation,proto3" json:"work_station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replenish) Reset() {
	*x = Replenish{}
	mi := &file_yfy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replenish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replenish) ProtoMessage() {}

func (x *Replenish) ProtoReflect() protoreflect.Message {
	mi := &file_yfy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replenish.ProtoReflect.Descriptor instead.
func (*Replenish) Descriptor() ([]byte, []int) {
	return file_yfy_proto_rawDescGZIP(), []int{2}
}

func (x *Replenish) GetTrayQty() int32 {
	if x != nil {
		return x.TrayQty
	}
	return 0
}

func (x *Replenish) GetWorkStation() string {
	if x != nil {
		return x.WorkStation
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Hb
	//	*ClientMessage_OrderInfo
	//	*ClientMessage_CallTray
	//	*ClientMessage_Replenish
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_yfy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_yfy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_yfy_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

func (x *ClientMessage) GetOrderInfo() *OrderInfo {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_OrderInfo); ok {
			return x.OrderInfo
		}
	}
	return nil
}

func (x *ClientMessage) GetCallTray() *CallTray {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CallTray); ok {
			return x.CallTray
		}
	}
	return nil
}

func (x *ClientMessage) GetReplenish() *Replenish {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Replenish); ok {
			return x.Replenish
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Hb struct {
	// when request id is 2
	Hb int32 `protobuf:"varint,2,opt,name=hb,proto3,oneof"`
}

type ClientMessage_OrderInfo struct {
	// when request id is 3
	OrderInfo *OrderInfo `protobuf:"bytes,3,opt,name=order_info,json=orderInfo,proto3,oneof"`
}

type ClientMessage_CallTray struct {
	// when request id is 4
	CallTray *CallTray `protobuf:"bytes,4,opt,name=call_tray,json=callTray,proto3,oneof"`
}

type ClientMessage_Replenish struct {
	// when request id is 5
	Replenish *Replenish `protobuf:"bytes,5,opt,name=replenish,proto3,oneof"`
}

func (*ClientMessage_Hb) isClientMessage_Payload() {}

func (*ClientMessage_OrderInfo) isClientMessage_Payload() {}

func (*ClientMessage_CallTray) isClientMessage_Payload() {}

func (*ClientMessage_Replenish) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Hb
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_yfy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_yfy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_yfy_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Hb struct {
	// request id 2 mean heartbeat
	Hb int32 `protobuf:"varint,2,opt,name=hb,proto3,oneof"`
}

func (*ServerMessage_Hb) isServerMessage_Payload() {}

var File_yfy_proto protoreflect.FileDescriptor

const file_yfy_proto_rawDesc = "" +
	"\n" +
	"\tyfy.proto\x12\x06yfy_pb\"\xba\x01\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpaper_count\x18\x02 \x01(\x05R\n" +
	"paperCount\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x19\n" +
	"\bbatch_no\x18\x04 \x01(\tR\abatchNo\x12!\n" +
	"\fwarehouse_no\x18\x05 \x01(\tR\vwarehouseNo\x12\x1b\n" +
	"\ttray_type\x18\x06 \x01(\tR\btrayType\"e\n" +
	"\bCallTray\x12\x1b\n" +
	"\ttray_type\x18\x01 \x01(\tR\btrayType\x12\x19\n" +
	"\btray_qty\x18\x02 \x01(\x05R\atrayQty\x12!\n" +
	"\fwork_station\x18\x03 \x01(\tR\vworkStation\"I\n" +
	"\tReplenish\x12\x19\n" +
	"\btray_qty\x18\x02 \x01(\x05R\atrayQty\x12!\n" +
	"\fwork_station\x18\x03 \x01(\tR\vworkStation\"\xc4\x01\n" +
	"\rClientMessage\x12\x10\n" +
	"\x02hb\x18\x02 \x01(\x05H\x00R\x02hb\x122\n" +
	"\n" +
	"order_info\x18\x03 \x01(\v2\x11.yfy_pb.OrderInfoH\x00R\torderInfo\x12/\n" +
	"\tcall_tray\x18\x04 \x01(\v2\x10.yfy_pb.CallTrayH\x00R\bcallTray\x121\n" +
	"\treplenish\x18\x05 \x01(\v2\x11.yfy_pb.ReplenishH\x00R\treplenishB\t\n" +
	"\apayload\",\n" +
	"\rServerMessage\x12\x10\n" +
	"\x02hb\x18\x02 \x01(\x05H\x00R\x02hbB\t\n" +
	"\apayload2N\n" +
	"\n" +
	"YFYService\x12@\n" +
	"\fYFYStreaming\x12\x15.yfy_pb.ClientMessage\x1a\x15.yfy_pb.ServerMessage(\x010\x01B\x19Z\x17kenmec/yfy/protoGen;genb\x06proto3"

var (
	file_yfy_proto_rawDescOnce sync.Once
	file_yfy_proto_rawDescData []byte
)

func file_yfy_proto_rawDescGZIP() []byte {
	file_yfy_proto_rawDescOnce.Do(func() {
		file_yfy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yfy_proto_rawDesc), len(file_yfy_proto_rawDesc)))
	})
	return file_yfy_proto_rawDescData
}

var file_yfy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yfy_proto_goTypes = []any{
	(*OrderInfo)(nil),     // 0: yfy_pb.OrderInfo
	(*CallTray)(nil),      // 1: yfy_pb.CallTray
	(*Replenish)(nil),     // 2: yfy_pb.Replenish
	(*ClientMessage)(nil), // 3: yfy_pb.ClientMessage
	(*ServerMessage)(nil), // 4: yfy_pb.ServerMessage
}
var file_yfy_proto_depIdxs = []int32{
	0, // 0: yfy_pb.ClientMessage.order_info:type_name -> yfy_pb.OrderInfo
	1, // 1: yfy_pb.ClientMessage.call_tray:type_name -> yfy_pb.CallTray
	2, // 2: yfy_pb.ClientMessage.replenish:type_name -> yfy_pb.Replenish
	3, // 3: yfy_pb.YFYService.YFYStreaming:input_type -> yfy_pb.ClientMessage
	4, // 4: yfy_pb.YFYService.YFYStreaming:output_type -> yfy_pb.ServerMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yfy_proto_init() }
func file_yfy_proto_init() {
	if File_yfy_proto != nil {
		return
	}
	file_yfy_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientMessage_Hb)(nil),
		(*ClientMessage_OrderInfo)(nil),
		(*ClientMessage_CallTray)(nil),
		(*ClientMessage_Replenish)(nil),
	}
	file_yfy_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_Hb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yfy_proto_rawDesc), len(file_yfy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yfy_proto_goTypes,
		DependencyIndexes: file_yfy_proto_depIdxs,
		MessageInfos:      file_yfy_proto_msgTypes,
	}.Build()
	File_yfy_proto = out.File
	file_yfy_proto_goTypes = nil
	file_yfy_proto_depIdxs = nil
}
