// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: yfy.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YFYService_YFYStreaming_FullMethodName = "/yfy_pb.YFYService/YFYStreaming"
)

// YFYServiceClient is the client API for YFYService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// bidirectional Streaming
type YFYServiceClient interface {
	// bidirectional Streaming
	YFYStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type yFYServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYFYServiceClient(cc grpc.ClientConnInterface) YFYServiceClient {
	return &yFYServiceClient{cc}
}

func (c *yFYServiceClient) YFYStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &YFYService_ServiceDesc.Streams[0], YFYService_YFYStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YFYService_YFYStreamingClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// YFYServiceServer is the server API for YFYService service.
// All implementations must embed UnimplementedYFYServiceServer
// for forward compatibility.
//
// bidirectional Streaming
type YFYServiceServer interface {
	// bidirectional Streaming
	YFYStreaming(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedYFYServiceServer()
}

// UnimplementedYFYServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYFYServiceServer struct{}

func (UnimplementedYFYServiceServer) YFYStreaming(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method YFYStreaming not implemented")
}
func (UnimplementedYFYServiceServer) mustEmbedUnimplementedYFYServiceServer() {}
func (UnimplementedYFYServiceServer) testEmbeddedByValue()                    {}

// UnsafeYFYServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YFYServiceServer will
// result in compilation errors.
type UnsafeYFYServiceServer interface {
	mustEmbedUnimplementedYFYServiceServer()
}

func RegisterYFYServiceServer(s grpc.ServiceRegistrar, srv YFYServiceServer) {
	// If the following call panics, it indicates UnimplementedYFYServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YFYService_ServiceDesc, srv)
}

func _YFYService_YFYStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(YFYServiceServer).YFYStreaming(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YFYService_YFYStreamingServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// YFYService_ServiceDesc is the grpc.ServiceDesc for YFYService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YFYService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yfy_pb.YFYService",
	HandlerType: (*YFYServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "YFYStreaming",
			Handler:       _YFYService_YFYStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "yfy.proto",
}
